In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/complaints.csv')
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2020-07-06,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,FL,346XX,NaN,Other,Web,2020-07-06,Closed with explanation,Yes,NaN,3730948
1,2019-12-26,Credit card or prepaid card,General-purpose credit card or charge card,"Advertising and marketing, including promotion...",Confusing or misleading advertising about the ...,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,CA,94025,NaN,Consent not provided,Web,2019-12-26,Closed with explanation,Yes,NaN,3477549
2,2020-05-08,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,These are not my accounts.,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,NV,89030,NaN,Consent provided,Web,2020-05-08,Closed with explanation,Yes,NaN,3642453
3,2024-01-05,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,Kindly address this issue on my credit report....,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,IL,60502,NaN,Consent provided,Web,2024-01-05,Closed with non-monetary relief,Yes,NaN,8113747
4,2024-01-21,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,NC,27401,Servicemember,Consent not provided,Web,2024-01-21,Closed with explanation,Yes,NaN,8191825

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15188499 entries, 0 to 15188498
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 str
 1   Product                       str
 2   Sub-product                   str
 3   Issue                         str
 4   Sub-issue                     str
 5   Consumer complaint narrative  str
 6   Company public response       str
 7   Company                       str
 8   State                         str
 9   ZIP code                      str
 10  Tags                          str
 11  Consumer consent provided?    str
 12  Submitted via                 str
 13  Date sent to company          str
 14  Company response to consumer  str
 15  Timely response?              str
 16  Consumer disputed?            str
 17  Complaint ID                  int64
dtypes: int64(1), str(17)
memory usage: 2.0 GB

In [42]:
data = df[['Product', 'Consumer complaint narrative']]

In [43]:
data = data.rename(columns={'Consumer complaint narrative': 'complaints', 'Product': 'product'})

In [44]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15188499 entries, 0 to 15188498
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   product     str
 1   complaints  str
dtypes: str(2)
memory usage: 231.8 MB

In [45]:
data.head()

,product,complaints
0,"Credit reporting, credit repair services, or o...",NaN
1,Credit card or prepaid card,NaN
2,"Credit reporting, credit repair services, or o...",These are not my accounts.
3,Credit reporting or other personal consumer re...,Kindly address this issue on my credit report....
4,Credit reporting or other personal consumer re...,NaN

In [46]:
data.isnull().sum()

product              0
complaints    11407901
dtype: int64

# Rename Product
- credit_reporting
- mortgage
- credit_card
- retail_banking
- loans
- debt_collection

In [47]:
data["product"].value_counts()

product
Credit reporting or other personal consumer reports                             9844643
Credit reporting, credit repair services, or other personal consumer reports    2163800
Debt collection                                                                 1089888
Mortgage                                                                         448259
Checking or savings account                                                      364460
Credit card                                                                      310916
Credit card or prepaid card                                                      206364
Money transfer, virtual currency, or money service                               177943
Credit reporting                                                                 140426
Student loan                                                                     126633
Vehicle loan or lease                                                             94437
Bank account or service                                                           86200
Consumer Loan                                                                     31559
Payday loan, title loan, personal loan, or advance loan                           30721
Payday loan, title loan, or personal loan                                         30625
Prepaid card                                                                      20948
Debt or credit management                                                          8721
Payday loan                                                                        5528
Money transfers                                                                    5354
Other financial service                                                            1056
Virtual currency                                                                     18
Name: count, dtype: int64

In [48]:
data["product"] = data["product"].replace(
    {
        "Credit reporting or other personal consumer reports": "credit_reporting",
        "Credit reporting, credit repair services, or other personal consumer reports": "credit_reporting",
        "Debt collection" : "debt_collection",
        "Mortgage" : "mortgage",
        "Checking or savings account": "retail_banking",
        "Credit card" : "credit_card",
        "Credit card or prepaid card" : "credit_card",
        "Money transfer, virtual currency, or money service": "retail_banking",
        "Credit reporting": "credit_reporting",
        "Student loan": "loans",
        "Vehicle loan or lease": "loans",
        "Bank account or service": "retail_banking",
        "Consumer Loan": "loans",
        "Payday loan, title loan, personal loan, or advance loan": "loans",
        "Payday loan, title loan, or personal loan": "loans",
        "Prepaid card": "credit_card",
        "Debt or credit management": "retail_banking",
        "Payday loan": "loans",
        "Money transfers": "retail_banking",
        "Other financial service": "retail_banking",
        "Virtual currency": "retail_banking"
    }
)

In [49]:
data["product"].value_counts()

product
credit_reporting    12148869
debt_collection      1089888
retail_banking        643752
credit_card           538228
mortgage              448259
loans                 319503
Name: count, dtype: int64

In [50]:
data.to_csv('data/product_complaints.csv', index=False)